-- Flyway 초기 마이그레이션 파일
-- 새로운 스키마 변경 시 V2__description.sql 형식으로 파일을 추가하세요.

-- pgvector 확장 설치
CREATE EXTENSION IF NOT EXISTS vector;

create table public.member
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    facebook_link  varchar(100),
    google_email   varchar(100)                                     not null,
    google_id      varchar(50),
    instagram_link varchar(100),
    nickname       varchar(30)                                      not null,
    plan           varchar(255)                                     not null
        constraint member_plan_check
            check ((plan)::text = ANY
                   ((ARRAY ['FREE'::character varying, 'BASIC'::character varying, 'ENTERPRISE'::character varying, 'ADMIN'::character varying])::text[])),
    profile_image  varchar(255),
    tiktok_link    varchar(100),
    twitter_link   varchar(100),
    deleted_at     timestamp(6),
    status         varchar(255) default 'ACTIVE'::character varying not null
        constraint member_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'WITHDRAWN'::character varying])::text[]))
);

create table public.report_log
(
    id                       bigint generated by default as identity
        primary key,
    advice_comment           bigint,
    advice_comment_content   varchar(400),
    analyze_status           varchar(255)
        constraint report_log_analyze_status_check
            check ((analyze_status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    comment                  bigint,
    comment_channel_avg      double precision,
    comment_topic_avg        double precision,
    concept                  integer,
    created_at               timestamp(6),
    delete_type              varchar(255),
    leave_analyze            text,
    like_channel_avg         double precision,
    like_count               bigint,
    like_topic_avg           double precision,
    logged_at                timestamp(6),
    negative_comment         bigint,
    negative_comment_content varchar(400),
    neutral_comment          bigint,
    neutral_comment_content  varchar(400),
    optimization             text,
    overview_status          varchar(255)
        constraint report_log_overview_status_check
            check ((overview_status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    positive_comment         bigint,
    positive_comment_content varchar(400),
    report_id                bigint,
    revisit                  integer,
    seo                      integer,
    summary                  text,
    title                    varchar(255),
    updated_at               timestamp(6),
    video_id                 bigint,
    view                     bigint,
    view_channel_avg         double precision,
    view_topic_avg           double precision
);

create table public.content_chunk
(
    id          serial
        primary key,
    source_type varchar(255)            not null,
    source_id   integer                 not null,
    content     text                    not null,
    chunk_index integer                 not null,
    embedding   vector(1536),
    meta        jsonb,
    created_at  timestamp default now() not null
);

create table public.channel
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    channel_hash_tag    varchar(255)
        constraint channel_channel_hash_tag_check
            check ((channel_hash_tag)::text = ANY
                   ((ARRAY ['NONE'::character varying, 'FILM_AND_ANIMATION'::character varying, 'AUTOS_AND_VEHICLES'::character varying, 'MUSIC'::character varying, 'PETS_AND_ANIMALS'::character varying, 'SPORTS'::character varying, 'SHORT_MOVIES'::character varying, 'TRAVEL_AND_EVENTS'::character varying, 'GAMING'::character varying, 'VIDEOBLOGGING'::character varying, 'PEOPLE_AND_BLOGS'::character varying, 'COMEDY'::character varying, 'ENTERTAINMENT'::character varying, 'NEWS_AND_POLITICS'::character varying, 'HOWTO_AND_STYLE'::character varying, 'EDUCATION'::character varying, 'SCIENCE_AND_TECHNOLOGY'::character varying, 'MOVIES'::character varying, 'ANIME_ANIMATION'::character varying, 'ACTION_ADVENTURE'::character varying, 'CLASSICS'::character varying, 'COMEDY_GENRE'::character varying, 'DOCUMENTARY'::character varying, 'DRAMA'::character varying, 'FAMILY'::character varying, 'FOREIGN'::character varying, 'HORROR'::character varying, 'SCI_FI_FANTASY'::character varying, 'THRILLER'::character varying, 'SHORTS'::character varying, 'SHOWS'::character varying, 'TRAILERS'::character varying])::text[])),
    channel_update_at   timestamp(6) not null,
    comment             bigint       not null,
    concept             varchar(255) not null,
    image               varchar(255) not null,
    join_date           timestamp(6) not null,
    like_count          bigint       not null,
    link                varchar(255) not null,
    name                varchar(255) not null,
    share               bigint       not null,
    subscribe           bigint       not null,
    target              varchar(255) not null,
    video_count         bigint       not null,
    view                bigint       not null,
    youtube_channel_id  varchar(255) not null
        constraint uka4oxy8ncu5ungs3dnxx7d21n4
            unique,
    youtube_playlist_id varchar(255) not null
        constraint ukitohem79mb2k3cvawgci9gffk
            unique,
    member_id           bigint       not null
        constraint ukhllnqrogls49smdk2v3e3es9a
            unique
        constraint fkbbldq0tg8bt76s1krc6wxlpr2
            references public.member
);

create table public.idea
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6),
    updated_at     timestamp(6),
    content        varchar(255) not null,
    hash_tag       varchar(255) not null,
    is_book_marked boolean      not null,
    title          varchar(100) not null,
    channel_id     bigint       not null
        constraint fkrwav9cshseh34cqxpvsc2u6no
            references public.channel
);

create table public.idea_log
(
    id             bigint generated by default as identity
        primary key,
    channel_id     bigint,
    content        varchar(255) not null,
    created_at     timestamp(6),
    hash_tag       varchar(255) not null,
    idea_id        bigint,
    is_book_marked boolean      not null,
    logged_at      timestamp(6),
    title          varchar(100) not null,
    update_at      timestamp(6)
);

create table public.member_agree
(
    id                      bigint generated by default as identity
        primary key,
    created_at              timestamp(6),
    updated_at              timestamp(6),
    day_content_email_agree boolean not null,
    marketing_email_agree   boolean not null,
    member_id               bigint  not null
        constraint fkidc8ol6y753cph4vuq9fa9scd
            references public.member
);

create table public.trend_keyword
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    keyword      varchar(50)  not null,
    keyword_type varchar(255) not null
        constraint trend_keyword_keyword_type_check
            check ((keyword_type)::text = ANY
                   ((ARRAY ['REAL_TIME'::character varying, 'CHANNEL'::character varying])::text[])),
    score        integer      not null,
    channel_id   bigint
        constraint fk7mh3nmn7nivbf8cllyx2l4jlx
            references public.channel
);

create table public.video
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    comment_count    bigint,
    description      varchar(5000),
    like_count       bigint,
    link             varchar(255),
    thumbnail        varchar(255),
    title            varchar(255),
    upload_date      timestamp(6),
    video_category   varchar(255)
        constraint video_video_category_check
            check ((video_category)::text = ANY
                   ((ARRAY ['NONE'::character varying, 'FILM_AND_ANIMATION'::character varying, 'AUTOS_AND_VEHICLES'::character varying, 'MUSIC'::character varying, 'PETS_AND_ANIMALS'::character varying, 'SPORTS'::character varying, 'SHORT_MOVIES'::character varying, 'TRAVEL_AND_EVENTS'::character varying, 'GAMING'::character varying, 'VIDEOBLOGGING'::character varying, 'PEOPLE_AND_BLOGS'::character varying, 'COMEDY'::character varying, 'ENTERTAINMENT'::character varying, 'NEWS_AND_POLITICS'::character varying, 'HOWTO_AND_STYLE'::character varying, 'EDUCATION'::character varying, 'SCIENCE_AND_TECHNOLOGY'::character varying, 'MOVIES'::character varying, 'ANIME_ANIMATION'::character varying, 'ACTION_ADVENTURE'::character varying, 'CLASSICS'::character varying, 'COMEDY_GENRE'::character varying, 'DOCUMENTARY'::character varying, 'DRAMA'::character varying, 'FAMILY'::character varying, 'FOREIGN'::character varying, 'HORROR'::character varying, 'SCI_FI_FANTASY'::character varying, 'THRILLER'::character varying, 'SHORTS'::character varying, 'SHOWS'::character varying, 'TRAILERS'::character varying])::text[])),
    view             bigint,
    youtube_video_id varchar(255) not null
        constraint uklfq9nxegvug5medlsa32lmjiy
            unique,
    channel_id       bigint       not null
        constraint fkfrbu2k83awmspohxv36yi6tgt
            references public.channel
);

create table public.report
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6),
    updated_at          timestamp(6),
    advice_comment      bigint,
    comment             bigint,
    comment_channel_avg double precision,
    comment_topic_avg   double precision,
    concept             integer,
    leave_analyze       text,
    like_channel_avg    double precision,
    like_count          bigint,
    like_topic_avg      double precision,
    negative_comment    bigint,
    neutral_comment     bigint,
    optimization        text,
    positive_comment    bigint,
    revisit             integer,
    seo                 integer,
    summary             text,
    title               varchar(255),
    view                bigint,
    view_channel_avg    double precision,
    view_topic_avg      double precision,
    video_id            bigint not null
        constraint fk5m7uvxjylkhb6g5j3yqh4ldpf
            references public.video,
    update_summary      varchar(1000)
);

create table public.comment
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    comment_type varchar(255) not null
        constraint comment_comment_type_check
            check ((comment_type)::text = ANY
                   ((ARRAY ['NEUTRAL'::character varying, 'POSITIVE'::character varying, 'NEGATIVE'::character varying, 'ADVICE_OPINION'::character varying])::text[])),
    content      text         not null,
    report_id    bigint       not null
        constraint fkn2m8whrfw1drq2c67d247br7c
            references public.report
);

create table public.task
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    analysis_status varchar(255) not null
        constraint task_analysis_status_check
            check ((analysis_status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    idea_status     varchar(255) not null
        constraint task_idea_status_check
            check ((idea_status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    overview_status varchar(255) not null
        constraint task_overview_status_check
            check ((overview_status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    report_id       bigint       not null
        constraint ukpqfff16ykollgowsv5ruo9441
            unique
        constraint fkqhrntwa4ll5gplvs23bdocep8
            references public.report
);
